apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: kube-logging
  labels:
    app: fluent-bit
data:
  parsers.conf: |
    # Docker JSON log format parser (For Kubernetes logs)
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

    # Multiline parser for Spring Boot logs
    [MULTILINE_PARSER]
        Name   springboot_multiline
        Type   regex
        Flush_Timeout 5
        Rule   "start_state"   "/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}/"  "cont"
        Rule   "cont"          "/^\s+/"  "cont"